const habits = [
    {
        id: 1,
        habit: "Drink Water",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 2,
        habit: "Stretch",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 3,
        habit: "Meal Prep",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 4,
        habit: "Read For 30 Minutes",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 5,
        habit: "Watch Ted Talk",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 6,
        habit: "10 Jumping Jacks Instead of Smoking",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 7,
        habit: "30 Minutes No Phone Time",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 8,
        habit: "Healthy Snacks",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 9,
        habit: "One Week Social Media Break",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 10,
        habit: "Deep Breathing Exercises",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 11,
        habit: "Take A Walk",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 12,
        habit: "One Month Sobriety Challenge",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 13,
        habit: "Pay it Forward Challenge",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 14,
        habit: "Sign Up to Volunteer for your Community",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 15,
        habit: "Floss Teeth",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 16,
        habit: "Clean One Area of Your Space",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 17,
        habit: "Make a New Budget",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 18,
        habit: "Create Something You Enjoy",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 19,
        habit: "Dance Like No One's Watching",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 20,
        habit: "Wake Up Same Time Everyday",
        morning: true,
        afternoon: false,
        evening: false,
    },
    {
        id: 21,
        habit: "Sleep Same Time Everyday",
        morning: false,
        afternoon: false,
        evening: true,
    },
    {
        id: 22,
        habit: "Set Out Outfit for Tomorrow",
        morning: false,
        afternoon: true,
        evening: true,
    },
    {
        id: 23,
        habit: "Set Coffee Maker",
        morning: false,
        afternoon: false,
        evening: true,
    },
    {
        id: 24,
        habit: "Reach Out to a Loved One",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 25,
        habit: "Clean Your Email Inbox",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 26,
        habit: "Skincare and SelfLove Challenge",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 27,
        habit: "Watch or Do Something that makes You Genuinely Laugh",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 28,
        habit: "Watch or Do Something that Genuinely Inspires You",
        morning: true,
        afternoon: true,
        evening: true,
    },
    {
        id: 29,
        habit: "Turn Appliances Off 1 hour Before Bed",
        morning: false,
        afternoon: false,
        evening: true,
    },
    {
        id: 30,
        habit: "Coffee and News to Start the Day",
        morning: true,
        afternoon: false,
        evening: false,
    },
]